repos:
  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
        types: [python]
        language_version: python3
        args: [ --config=pyproject.toml, --check ]
        verbose: true
