site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Guides & Getting Started:
    - 'Using with the Quix Platform': quix-platform.md
    - 'Serialization': serialization.md
    - 'Stateful Processing': stateful-processing.md
    - 'Streaming DataFrames': streamingdataframe.md
    - 'Upgrading from Legacy QuixStreams': upgrading-legacy.md
  - API Docs:
    - Typical Usage:
      - Application: api-reference/application.md
      - DataFrames: api-reference/dataframe.md
      - Topics & Serialization: api-reference/topics-serdes.md
      - Quix Platform API: api-reference/quix-platform-api.md
    - Complete (advanced users): api-reference/quixstreams.md