site_name: Quix Docs
site_description: Quix Streams Documentation
repo_url: https://github.com/quixio/quix-streams/
edit_uri: tree/main

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Detailed Guides:
    - An Example Application: example.md
    - Using with the Quix Platform: quix-platform.md
    - Serialization: serialization.md
    - Stateful Processing: stateful-processing.md
    - Streaming DataFrame: streamingdataframe.md
    - Upgrading from Legacy QuixStreams: upgrading-legacy.md
  - API Docs:
    - Essentials:
      - Application: api-reference/application.md
      - Streaming DataFrame: api-reference/dataframe.md
      - Topics & Serialization: api-reference/topics-serdes.md
      - Quix Platform API: api-reference/quix-platform-api.md
    - Complete (rarely needed): api-reference/quixstreams.md